GET http://localhost:8080/api/employees/

###
POST http://localhost:8080/api/employees/
Content-Type: application/json

{
  "name": "Valaki",
  "level": "Godlike",
  "position": "Joker"
}

###
DELETE http://localhost:8080/api/employees/65b7a407660d33d85ef81be8

###
PATCH http://localhost:8080/api/employees/65b7a41c660d33d85ef81bef
Content-Type:  application/json

{
  "name": "asd"
}
